name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 12.x
            
    #instalar as dependencias
    - name: instalar as dependencias
      run: yarn
     
     #executar build
    - name: run build
      run: yarn build

    #copiar codigo para Digital Ocean
    - name: copy file dist to DigitalOcean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}        
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: ".,!node_modules,!dist/shared/infra/typeorm/index.js"
        target: "~/app/Gobarber-Backend"
  
    
    - name: instalar as dependencias
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}        
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/app/Gobarber-Backend
          yarn
          yarn typeorm migration:run
          pm2 restart gobarber
    
#executar "yarn" na Digital Ocean
#executar as migrations TypeORM
#Restart no servidor node.js
