name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
      with:
        node-version: 12.x
            
    #instalar as dependencias
    - name: instalar as dependencias
      run: yarn
     
     #executar build
    - name: run build
      run: yarn

    #copiar a pasta dist na Digital Ocean
    - name: copy file dist to DigitalOcean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}        
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "dist"
        target: "test"
  
#substituir o codigo existente na pasta "dist" pelo novo codigo
#executar "yarn" na Digital Ocean
#executar as migrations TypeORM
#Restart no servidor node.js
